version: '3'
services:
  geth:
    image: ethereum/client-go
    command: --networkid 66 --nodiscover --verbosity 5
    volumes:
      - "./geth/runtime:/root/.ethereum"
    ports:
      - "30303:30303"